
SELECT NAME FROM v$database;

Select Name from v$tablespace;

DROP USER "QA7CLARITY501REPORTUSER" CASCADE;
DROP USER "QA7CLARITY501LOOKUPUSER" CASCADE;
DROP USER "QA7CLARITY501" CASCADE;
DROP TABLESPACE "CLARITY501" INCLUDING CONTENTS AND DATAFILES;

-- CLARITY501 A

CREATE SMALLFILE TABLESPACE "CLARITY501"
DATAFILE SIZE 500M AUTOEXTEND ON NEXT 50M
MAXSIZE UNLIMITED
LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

-- Create standard Clarity Usert

CREATE USER "QA7CLARITY501"  IDENTIFIED BY "QA7CLARITY501" DEFAULT TABLESPACE "CLARITY501" ACCOUNT UNLOCK;
GRANT UNLIMITED TABLESPACE TO "QA7CLARITY501";
GRANT "CONNECT" TO "QA7CLARITY501";
GRANT "RESOURCE" TO "QA7CLARITY501";
GRANT CREATE VIEW TO "QA7CLARITY501";
GRANT CREATE MATERIALIZED VIEW TO "QA7CLARITY501";
GRANT CREATE PROCEDURE TO "QA7CLARITY501";
GRANT CREATE PUBLIC SYNONYM TO "QA7CLARITY501";
GRANT CREATE SEQUENCE TO "QA7CLARITY501";
GRANT CREATE SYNONYM TO "QA7CLARITY501";
GRANT CREATE TABLE TO "QA7CLARITY501";
GRANT CREATE TRIGGER TO "QA7CLARITY501";
GRANT CREATE TYPE TO "QA7CLARITY501";
GRANT CREATE ANY CONTEXT TO "QA7CLARITY501";

-- Create Reporting (ETL) User

CREATE USER "QA7CLARITY501REPORTUSER"  IDENTIFIED BY "QA7CLARITY501" DEFAULT TABLESPACE "CLARITY501" ACCOUNT UNLOCK;
GRANT UNLIMITED TABLESPACE TO "QA7CLARITY501REPORTUSER";
GRANT "CONNECT" TO "QA7CLARITY501REPORTUSER";
GRANT "RESOURCE" TO "QA7CLARITY501REPORTUSER";
GRANT CREATE VIEW TO "QA7CLARITY501REPORTUSER";
GRANT CREATE MATERIALIZED VIEW TO "QA7CLARITY501REPORTUSER";
GRANT CREATE PROCEDURE TO "QA7CLARITY501REPORTUSER";
GRANT CREATE PUBLIC SYNONYM TO "QA7CLARITY501REPORTUSER";
GRANT CREATE SEQUENCE TO "QA7CLARITY501REPORTUSER";
GRANT CREATE TABLE TO "QA7CLARITY501REPORTUSER";
GRANT CREATE TRIGGER TO "QA7CLARITY501REPORTUSER";


-- Create Lookup User

CREATE USER "QA7CLARITY501LOOKUPUSER"  IDENTIFIED BY "QA7CLARITY501" DEFAULT TABLESPACE "CLARITY501" ACCOUNT UNLOCK;
GRANT UNLIMITED TABLESPACE TO "QA7CLARITY501LOOKUPUSER";
GRANT "CONNECT" TO "QA7CLARITY501LOOKUPUSER";
GRANT "RESOURCE" TO "QA7CLARITY501LOOKUPUSER";
GRANT CREATE VIEW TO "QA7CLARITY501LOOKUPUSER";
GRANT CREATE MATERIALIZED VIEW TO "QA7CLARITY501LOOKUPUSER";
GRANT CREATE PROCEDURE TO "QA7CLARITY501LOOKUPUSER";
GRANT CREATE PUBLIC SYNONYM TO "QA7CLARITY501LOOKUPUSER";
GRANT CREATE SEQUENCE TO "QA7CLARITY501LOOKUPUSER";
GRANT CREATE SYNONYM TO "QA7CLARITY501LOOKUPUSER";
GRANT CREATE TABLE TO "QA7CLARITY501LOOKUPUSER";
GRANT CREATE TRIGGER TO "QA7CLARITY501LOOKUPUSER";
GRANT CREATE TYPE TO "QA7CLARITY501LOOKUPUSER";


PURGE RECYCLEBIN;
COMMIT;

ALTER SESSION SET CURRENT_SCHEMA = "QA7CLARITY501";

@/tmp/OracleSetup/json_v1_0_5/install.sql;
COMMIT;

EXIT

